{{- if .Values.environment.hasSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  SESSION_SECRET: ${ServiceBusInspectorSessionSecret}
  TENANT_ID: ${ServiceBusInspectorTenantId}
  CLIENT_ID: ${ServiceBusInspectorClientId}
  CLIENT_SECRET: ${ServiceBusInspectorClientSecret}
  SUBSCRIPTION_ID: ${ServiceBusInspectorSubscriptionId}
{{- end }}
